name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - use: action/checkout@v2
      - name: Run a one-line scripact
        run: echo hello, world!
      - name: run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
